### ISSUE TITLE
Confused on What you Did to Code

### ISSUE THREAD

**Issue by DrakenZA** [materight/RepNet-pytorch#5]
Im really confused on this one. The original repo, would let you feed as many frames as you want, and get the score for rep of each frame.

When using this repo, it doesnt provide the original functionally that allows for this, it also takes a 10sec video, 'says' its only checking 1 second for some reason, and then it outputs a 6 sec video ? Seems all over the place.

Would it be possible to get the original functionally back ? This acts more like a demo or showcase that workable code. Or am i missing something.

**Comment by materight** [comment]
The script only keeps a number of frames multiple of 64 (after the stride) to match the size of the temporal matrix, any additional frame is dropped. In the original script I think they just repeated the last frame to match the expected length. I didn't do that to avoid weird scores at the end of the video, but feel free to make a PR if you want to add support for the same behavior.

The goal of this repo was to port the model to pytorch so it can be used in other projects, the `run.py` script is just for showcase and testing.

**Comment by DrakenZA** [comment]
Thanks for the reply. Ya i did attempt to try get the original script used working, but my knowledge on the base ML stuff is pretty weak hehe.

Regardless, thanks for porting.
